substitutions:
  device_name: master8266
  friendly_name: Master Switch

## Boilerplate

esphome:
  name: ${device_name}

esp8266:
  board: huzzah

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: Fallback ${device_name}

captive_portal:

logger:

api:

ota:

## Device-specific

binary_sensor:
  - platform: gpio
    pin:
      number: 13
      mode:
        input: true
        pullup: true
    name: ${friendly_name} Button

sensor:
  - platform: dht
    pin: 2
    temperature:
      name: "Hall Temperature"
    humidity:
      name: "Hall Humidity"
    update_interval: 60s
