substitutions:
  device_name: plantwifi2
  friendly_name: "Plant Wifi 2"
  lower_percentage: "20"
  upper_percentage: "60"
  led_brightness: "20%"

## Boilerplate

esphome:
  name: ${device_name}

esp32:
  board: m5stack-atom
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: Fallback ${device_name}

captive_portal:

logger:

api:

ota:

## Device-specific

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: 27
    num_leds: 1
    rgb_order: GRB
    id: onboard
    name: ${friendly_name} Light

sensor:
  - platform: adc
    pin: 32
    name: ${friendly_name} Moisture %
    attenuation: auto
    update_interval: 60s
    unit_of_measurement: "%"
    filters:
    - calibrate_linear:
        - 2.57 -> 0.00
        - 1.28 -> 100.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0
    on_value_range:
      - below: ${lower_percentage}
        then:
          - light.turn_on:
              id: onboard
              brightness: ${led_brightness}
              red: 100%
              green: 0%
              blue: 0%
      - above: ${lower_percentage}
        below: ${upper_percentage}
        then:
          - light.turn_on:
              id: onboard
              brightness: ${led_brightness}
              red: 0%
              green: 100%
              blue: 0%
      - above: ${upper_percentage}
        then:
          - light.turn_on:
              id: onboard
              brightness: ${led_brightness}
              red: 0%
              green: 0%
              blue: 100%


# Max: 2.57
# Min: 1.28
# Range: 1.29
# 1.29/3 = 0.43
# 1.28 - 1.71 WET
# 1.71 - 2.14 OK
# 2.14 - 2.57 DRY
